package test;
import java.util.Timer;  
import java.util.TimerTask;  
  
public class TimerTest {  
    public static void main(String[] args) {  
    	System.out.println("定时开始！");
        // TODO todo.generated by zoer  
        Timer timer = new Timer();  
        timer.schedule(new MyTask(), 1000, 2000); 
        System.out.println("定时结束！");
    }  
}  
  
class MyTask extends TimerTask {  
  
    @Override  
    public void run() {  
        System.out.println("dddd");  
    }  
  
}