
package com.zjl.study.springcxf.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-28T16:59:28.002+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class HelloWorldService_HelloWorldServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("com:zjl:study:springcxf:webservice", "HelloWorldServiceImplService");

    private HelloWorldService_HelloWorldServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = HelloWorldServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        HelloWorldServiceImplService ss = new HelloWorldServiceImplService(wsdlURL, SERVICE_NAME);
        HelloWorldService port = ss.getHelloWorldServiceImplPort();  
        
        {
        System.out.println("Invoking sayHi...");
        java.lang.String _sayHi_text = "";
        java.lang.String _sayHi__return = port.sayHi(_sayHi_text);
        System.out.println("sayHi.result=" + _sayHi__return);


        }
        {
        System.out.println("Invoking sayHiToUser...");
        com.zjl.study.springcxf.client.User _sayHiToUser_arg0 = null;
        java.lang.String _sayHiToUser__return = port.sayHiToUser(_sayHiToUser_arg0);
        System.out.println("sayHiToUser.result=" + _sayHiToUser__return);


        }
        {
        System.out.println("Invoking sayHiToUserList...");
        java.util.List<com.zjl.study.springcxf.client.User> _sayHiToUserList_arg0 = null;
        java.util.List<java.lang.String> _sayHiToUserList__return = port.sayHiToUserList(_sayHiToUserList_arg0);
        System.out.println("sayHiToUserList.result=" + _sayHiToUserList__return);


        }

        System.exit(0);
    }

}
