package com.zjl.study.springcxf.client;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-28T16:59:28.051+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "HelloWorldServiceImplService", 
                  wsdlLocation = "file:/C:/Users/ADMINI~1/AppData/Local/Temp/tempdir8954714832316027243.tmp/HelloWorldService_1.wsdl",
                  targetNamespace = "com:zjl:study:springcxf:webservice") 
public class HelloWorldServiceImplService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("com:zjl:study:springcxf:webservice", "HelloWorldServiceImplService");
    public final static QName HelloWorldServiceImplPort = new QName("com:zjl:study:springcxf:webservice", "HelloWorldServiceImplPort");
    static {
        URL url = null;
        try {
            url = new URL("file:/C:/Users/ADMINI~1/AppData/Local/Temp/tempdir8954714832316027243.tmp/HelloWorldService_1.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(HelloWorldServiceImplService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "file:/C:/Users/ADMINI~1/AppData/Local/Temp/tempdir8954714832316027243.tmp/HelloWorldService_1.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public HelloWorldServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public HelloWorldServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public HelloWorldServiceImplService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public HelloWorldServiceImplService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public HelloWorldServiceImplService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public HelloWorldServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorldServiceImplPort")
    public HelloWorldService getHelloWorldServiceImplPort() {
        return super.getPort(HelloWorldServiceImplPort, HelloWorldService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns HelloWorldService
     */
    @WebEndpoint(name = "HelloWorldServiceImplPort")
    public HelloWorldService getHelloWorldServiceImplPort(WebServiceFeature... features) {
        return super.getPort(HelloWorldServiceImplPort, HelloWorldService.class, features);
    }

}
