
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.zjl.study.springcxf.client;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-28T16:59:28.035+08:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "HelloWorldServiceImplService",
                      portName = "HelloWorldServiceImplPort",
                      targetNamespace = "com:zjl:study:springcxf:webservice",
                      wsdlLocation = "file:/C:/Users/ADMINI~1/AppData/Local/Temp/tempdir8954714832316027243.tmp/HelloWorldService_1.wsdl",
                      endpointInterface = "com.zjl.study.springcxf.client.HelloWorldService")
                      
public class HelloWorldServiceImplPortImpl implements HelloWorldService {

    private static final Logger LOG = Logger.getLogger(HelloWorldServiceImplPortImpl.class.getName());

    /* (non-Javadoc)
     * @see com.zjl.study.springcxf.client.HelloWorldService#sayHi(java.lang.String  text )*
     */
    public java.lang.String sayHi(java.lang.String text) { 
        LOG.info("Executing operation sayHi");
        System.out.println(text);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zjl.study.springcxf.client.HelloWorldService#sayHiToUser(com.zjl.study.springcxf.client.User  arg0 )*
     */
    public java.lang.String sayHiToUser(com.zjl.study.springcxf.client.User arg0) { 
        LOG.info("Executing operation sayHiToUser");
        System.out.println(arg0);
        try {
            java.lang.String _return = "";
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see com.zjl.study.springcxf.client.HelloWorldService#sayHiToUserList(java.util.List<com.zjl.study.springcxf.client.User>  arg0 )*
     */
    public java.util.List<java.lang.String> sayHiToUserList(java.util.List<com.zjl.study.springcxf.client.User> arg0) { 
        LOG.info("Executing operation sayHiToUserList");
        System.out.println(arg0);
        try {
            java.util.List<java.lang.String> _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
