package com.zjl.study.springcxf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-28T16:59:28.045+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "com:zjl:study:springcxf:webservice", name = "HelloWorldService")
@XmlSeeAlso({ObjectFactory.class})
public interface HelloWorldService {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "com:zjl:study:springcxf:webservice", className = "com.zjl.study.springcxf.client.SayHi")
    @WebMethod
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "com:zjl:study:springcxf:webservice", className = "com.zjl.study.springcxf.client.SayHiResponse")
    public java.lang.String sayHi(
        @WebParam(name = "text", targetNamespace = "")
        java.lang.String text
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHiToUser", targetNamespace = "com:zjl:study:springcxf:webservice", className = "com.zjl.study.springcxf.client.SayHiToUser")
    @WebMethod
    @ResponseWrapper(localName = "sayHiToUserResponse", targetNamespace = "com:zjl:study:springcxf:webservice", className = "com.zjl.study.springcxf.client.SayHiToUserResponse")
    public java.lang.String sayHiToUser(
        @WebParam(name = "arg0", targetNamespace = "")
        com.zjl.study.springcxf.client.User arg0
    );

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "sayHiToUserList", targetNamespace = "com:zjl:study:springcxf:webservice", className = "com.zjl.study.springcxf.client.SayHiToUserList")
    @WebMethod
    @ResponseWrapper(localName = "sayHiToUserListResponse", targetNamespace = "com:zjl:study:springcxf:webservice", className = "com.zjl.study.springcxf.client.SayHiToUserListResponse")
    public java.util.List<java.lang.String> sayHiToUserList(
        @WebParam(name = "arg0", targetNamespace = "")
        java.util.List<com.zjl.study.springcxf.client.User> arg0
    );
}
