package com.lenovo.lesc.validation;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-17T17:06:13.089+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebServiceClient(name = "ValidationService", 
                  wsdlLocation = "http://uat-lesc.lenovo.com/ws/validation.wsdl",
                  targetNamespace = "http://www.lenovo.com/lesc/validation") 
public class ValidationService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://www.lenovo.com/lesc/validation", "ValidationService");
    public final static QName ValidationSoap11 = new QName("http://www.lenovo.com/lesc/validation", "ValidationSoap11");
    static {
        URL url = null;
        try {
            url = new URL("http://uat-lesc.lenovo.com/ws/validation.wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(ValidationService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://uat-lesc.lenovo.com/ws/validation.wsdl");
        }
        WSDL_LOCATION = url;
    }

    public ValidationService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public ValidationService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ValidationService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public ValidationService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public ValidationService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public ValidationService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns Validation
     */
    @WebEndpoint(name = "ValidationSoap11")
    public Validation getValidationSoap11() {
        return super.getPort(ValidationSoap11, Validation.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns Validation
     */
    @WebEndpoint(name = "ValidationSoap11")
    public Validation getValidationSoap11(WebServiceFeature... features) {
        return super.getPort(ValidationSoap11, Validation.class, features);
    }

}
