
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package com.lenovo.lesc.validation;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-17T17:06:13.018+08:00
 * Generated source version: 3.1.6
 * 
 */

@javax.jws.WebService(
                      serviceName = "ValidationService",
                      portName = "ValidationSoap11",
                      targetNamespace = "http://www.lenovo.com/lesc/validation",
                      wsdlLocation = "http://uat-lesc.lenovo.com/ws/validation.wsdl",
                      endpointInterface = "com.lenovo.lesc.validation.Validation")
                      
public class ValidationSoap11Impl implements Validation {

    private static final Logger LOG = Logger.getLogger(ValidationSoap11Impl.class.getName());

    /* (non-Javadoc)
     * @see com.lenovo.lesc.validation.Validation#validation(com.lenovo.lesc.validation.ValidationRequest  validationRequest )*
     */
    public com.lenovo.lesc.validation.ValidationResponse validation(ValidationRequest validationRequest) { 
        LOG.info("Executing operation validation");
        System.out.println(validationRequest);
        try {
            com.lenovo.lesc.validation.ValidationResponse _return = null;
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
