
package com.lenovo.lesc.validation;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2017-05-17T17:06:12.756+08:00
 * Generated source version: 3.1.6
 * 
 */
public final class Validation_ValidationSoap11_Client {

    private static final QName SERVICE_NAME = new QName("http://www.lenovo.com/lesc/validation", "ValidationService");

    private Validation_ValidationSoap11_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = ValidationService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        ValidationService ss = new ValidationService(wsdlURL, SERVICE_NAME);
        Validation port = ss.getValidationSoap11();  
        
        {
        System.out.println("Invoking validation...");
        com.lenovo.lesc.validation.ValidationRequest _validation_validationRequest = null;
        com.lenovo.lesc.validation.ValidationResponse _validation__return = port.validation(_validation_validationRequest);
        System.out.println("validation.result=" + _validation__return);


        }

        System.exit(0);
    }

}
